name: TerrainControl
version: 1.2.11
description: Generates a worlds.
authors: ['Khorn']
main: com.Khorn.TerrainControl.TCPlugin
load: startup
commands:
    tc:
        description: TerrainControl commands
        usage: |
              /<command> <check> [world] - Checks TC is enable for this world.
              /<command> <reload> [world] - Reload config
              /<command> <biome> [-f] - Show current chunk biome and block stats